### ISSUE TITLE
'minimal' stdlib support

### ISSUE THREAD

**Issue by mko-io** [madmachineio/MadMachineIDERelease#1]
Hi,
Firstly, I've been tracing your project for a while, so just want to say hi, and making swift working on MCU is very valuable, and I know it's a very difficult task including low level build, runtime, IDE and libraries, so just let your know what you are a very capable and  you've been doing is a great work

Second there's a [commit](https://github.com/apple/swift/pull/33427/files) on swift repo to enable a "minimal" stdlib, I think this could be very useful for your embedded mcu.

Thanks

**Comment by andy0808** [comment]
> Hi,
> Firstly, I've been tracing your project for a while, so just want to say hi, and making swift working on MCU is very valuable, and I know it's a very difficult task including low level build, runtime, IDE and libraries, so just let your know what you are a very capable and you've been doing is a great work
> 
> Second there's a [commit](https://github.com/apple/swift/pull/33427/files) on swift repo to enable a "minimal" stdlib, I think this could be very useful for your embedded mcu.
> 
> Thanks

Hi mko-io, thank you for your interest : ) Indeed, it's really a complicated project and there's no doubt more and more tough work are wating for us. It's absolutely impossible for me to do them alone, a lot of friends are helping me. thanks them so much : ) In my plan, this year I still have to focus on the infrastructure, and next year would be a right time to show the power of Swift on MCUs. All the software would be open sourced step by step. Hope we could make something really cool in the near future.

And thanks for your information. It would be very useful when I update the Swift compiler next time.

I don't know if you have joined our [community](https://discord.gg/zZ9bFHK), we would give all the latest information there. Any suggestion is welcomed!

**Comment by mko-io** [comment]
Your plan seems promising, the infrastructures are the hard parts in the beginning, but future is bright.

the link for community is invalid, could you send me another one, I'd link to join your guys.

**Comment by andy0808** [comment]
Hi,

The link is a Discord server, I checked it and it seems no problem. You may need to register before join in.

It's a very good platform for real time communication.

**Comment by mko-io** [comment]
I've finally figured out how to make Discord work, thanks
